from __future__ import unicode_literals, print_function, division
from io import open
import unicodedata
import string
import re
import random
import time
import math
import torch
import torch.nn as nn
from torch import optim
import torch.nn.functional as F
import matplotlib.pyplot as plt
plt.switch_backend('agg')
import matplotlib.ticker as ticker
import numpy as np
from os import system
from nltk.translate.bleu_score import SmoothingFunction, sentence_bleu
from dataloader import WordDataset, WordTransoformer
from torch.utils.data import DataLoader
from cvae import CVAE
from torch.utils.tensorboard import SummaryWriter
import time
import sys

"""========================================================================================
The sample.py includes the following template functions:

1. Encoder, decoder
2. Training function
3. BLEU-4 score function
4. Gaussian score function

You have to modify them to complete the lab.
In addition, there are still other functions that you have to 
implement by yourself.

1. The reparameterization trick
2. Your own dataloader (design in your own way, not necessary Pytorch Dataloader)
3. Output your results (BLEU-4 score, conversion words, Gaussian score, generation words)
4. Plot loss/score
5. Load/save weights

There are some useful tips listed in the lab assignment.
You should check them before starting your lab.
========================================================================================"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#----------Hyper Parameters----------#
lr = 0.05
epochs = 10
latent_size = 32

################################
#Example inputs of compute_bleu
################################
#The target word
reference = 'accessed'
#The word generated by your model
output = 'access'

#compute BLEU-4 score
def compute_bleu(output, reference):
    cc = SmoothingFunction()
    if len(reference) == 3:
        weights = (0.33,0.33,0.33)
    else:
        weights = (0.25,0.25,0.25,0.25)
    return sentence_bleu([reference], output,weights=weights,smoothing_function=cc.method1)


"""============================================================================
example input of Gaussian_score

words = [['consult', 'consults', 'consulting', 'consulted'],
['plead', 'pleads', 'pleading', 'pleaded'],
['explain', 'explains', 'explaining', 'explained'],
['amuse', 'amuses', 'amusing', 'amused'], ....]

the order should be : simple present, third person, present progressive, past
============================================================================"""

def Gaussian_score(words):
    words_list = []
    score = 0
    yourpath = 'dataset/train.txt'#should be your directory of train.txt
    with open(yourpath,'r') as fp:
        for line in fp:
            word = line.split(' ')
            word[3] = word[3].strip('\n')
            words_list.extend([word])
        for t in words:
            for i in words_list:
                if t == i:
                    score += 1
    return score/len(words)


def asMinutes(s):
    m = math.floor(s / 60)
    s -= m * 60
    return '%dm %ds' % (m, s)


def timeSince(since, percent):
    now = time.time()
    s = now - since
    es = s / (percent)
    rs = es - s
    return '%s (- %s)' % (asMinutes(s), asMinutes(rs))

def criterion(predict_distribution, target_distribution, mu, logvar):
    cross_entropy = nn.CrossEntropyLoss()
    reconstruction_loss = cross_entropy(predict_distribution, target_distribution)

    # KL(N(mu, logvar)||N(0,1))
    # multivariate Gaussian kl
    kl_loss = -0.5 * torch.sum(1 + logvar - mu**2 - logvar.exp())

    return reconstruction_loss, kl_loss

def train(model, dataloader, optimizer, transformer, kl_weight):
    KL_weight = 0 
    total_BLEU_score = 0
    total_rc_loss = 0
    total_kl_loss = 0
    model.train()
    for times, (word_tensor, tense_tensor) in enumerate(dataloader):
        optimizer.zero_grad()
        word_tensor = word_tensor[0]
        tense_tensor = tense_tensor[0]
        word_tensor, tense_tensor = word_tensor.to(device), tense_tensor.to(device)
        output, predict_distribution, mean, log_var = model(word_tensor, tense_tensor)
        reconstruction_loss, kl_loss = criterion(predict_distribution, word_tensor.view(-1), mean, log_var)
        if KL_weight >= 1:
            KL_weight = 1 
        else:
            KL_weight = KL_weight + (times+1) * 0.01
        loss = reconstruction_loss + KL_weight * kl_loss
        total_rc_loss += reconstruction_loss
        total_kl_loss += kl_loss
        loss.backward()
        optimizer.step()

        predict = transformer.tensor2words(output)
        target = transformer.tensor2words(word_tensor) 
        total_BLEU_score += compute_bleu(predict, target)
        if times % 200 == 0:
            print('Predict: ',predict) 
            print('Origin: ',target)
            print('Reconstruction loss: %f\nKL loss: %f\n---------------------' % (reconstruction_loss, kl_loss))

    return total_rc_loss.item(), total_kl_loss.item(), total_BLEU_score

def evaluate(model, dataloader, tense_list):
    with torch.no_grad():
        model.eval()
        total_BLEU_score = 0
        predict_list = []
        for times, (word_tensor, tense_tensor, target) in enumerate(dataloader):
            word_tensor = word_tensor[0]
            tense_tensor = tense_tensor[0]
            target = target[0]
            word_tensor, tense_tensor = word_tensor.to(device), tense_tensor.to(device)
            output, predict_distribution, mean, log_var = model(word_tensor, tense_tensor)

            predict = transformer.tensor2words(output)
            total_BLEU_score += compute_bleu(predict, target)
            
            predict_list.append(predict)
        
        # Gaussian score
        words = []
        for i in range(100):
            latent = torch.randn(1, 1, latent_size).to(device)
            words.extend(model.generate_words(latent, tense_list))
        for i in range(len(words)):
            words[i] = transformer.tensor2words(words[i])
        gaussian_score = Gaussian_score(words)
      
    return total_BLEU_score/len(dataloader.dataset), predict_list, gaussian_score, words

def record_score(bleu_score, gaussian_score, predict_list, generate_words, dataloader, transformer):
    bleu_record = open('bleu_record.txt', 'w')
    for i, (word_tensor, tense_tensor, target) in enumerate(dataloader):
        word_tensor = word_tensor[0]
        target = target[0]
        input_word = transformer.tensor2words(word_tensor)
        print('----------------', file=bleu_record)
        print('Input: ', input_word, file=bleu_record)
        print('Target: ', target, file=bleu_record)
        print('Prediction: ', predict_list[i], file=bleu_record) 
        print('----------------\n', file=bleu_record)

    print('Average BLEI-4 score: ', bleu_score, file=bleu_record)
    bleu_record.close()
    
    gaussian_record = open('gaussian_record.txt', 'w')
    for i in range(0,len(generate_words),4):
        print(generate_words[i] + ', ' + generate_words[i+1] + ', ' + generate_words[i+2] + ', ' + generate_words[i+3], file=gaussian_record)
    print('Gaussian score: ', gaussian_score, file=gaussian_record)
    gaussian_record.close()

def getKLWeight(kl_weight, dataset_size, strategy):
    warmup = 5
    kl_weight = min(1, kl_weight + 1./(warmup * dataset_size))
    if strategy == 'cyclical':
        if epoch % cycle == 0:
            kl_weight = 0.1
    elif strategy != 'mono':
        print('Unkown strategy')
        exit()

    return kl_weight        

if __name__ == '__main__':
    train_dataset = WordDataset('train')
    test_dataset = WordDataset('test')
    max_length = train_dataset.max_length + 5
    train_dataloader = DataLoader(train_dataset, batch_size=1, shuffle=True)
    test_dataloader = DataLoader(test_dataset, batch_size=1, shuffle=True)
    tense_list = test_dataloader.dataset.tense2idx.values()
    
    model = CVAE(max_length)
    model = model.to(device)
    if len(sys.argv) > 1:
        state_dict = torch.load(sys.argv[1])
        model.load_state_dict(state_dict)
    optimizer = optim.SGD(model.parameters(), lr=lr)
    transformer = WordTransoformer()
    trainset_size = len(train_dataloader.dataset)
    testset_size = len(test_dataloader.dataset)
    writer = SummaryWriter('logs/')
    
    start = time.time()
    best_bleu_score = 0
    kl_weight = 0.1
    for epoch in range(epochs):
        kl_weight = getKLWeight(kl_weight, trainset_size, 'mono')
        rc_loss, kl_loss, bleu_score = train(model, train_dataloader, optimizer, transformer, kl_weight)
        average_bleu_score, predict_list, gaussian_score, generate_words = evaluate(model, test_dataloader, tense_list)
        writer.add_scalar('Loss/reconstruction loss', rc_loss/trainset_size, epoch+1)
        writer.add_scalar('Loss/KL loss', kl_loss/trainset_size, epoch+1)
        writer.add_scalar('BLEU-4 score', average_bleu_score, epoch+1)
        print('Epoch ', epoch+1)
        print('Average Reconstruction loss: %f\n Average KL loss: %f' % (rc_loss/trainset_size, kl_loss/trainset_size))
        print('Average BLEU-4 score: ', average_bleu_score)
        
        if average_bleu_score > best_bleu_score:
            record_score(average_bleu_score, gaussian_score, predict_list, generate_words, test_dataloader, transformer)

        torch.save(model.state_dict(), 'model/checkpoint' + str(epoch) + '.pkl')
    end = time.time()
    print('Total training time: ' + str((end - start)//60) + ' minutess')